# External Network Load Balancer Service for CUDA Evaluation Server
# WARNING: This exposes the service to the internet - use with caution
# Consider using nlb-internal-service.yaml with SSM tunneling for better security
apiVersion: v1
kind: Service
metadata:
  name: cuda-eval-nlb-external
  namespace: hyperpod-ns-silverhand
  labels:
    app: cuda-eval-server-v2
    service-type: nlb-external
  annotations:
    # Network Load Balancer configuration
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # Internet-facing scheme - accessible from the internet
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    # Cross-zone load balancing for better availability
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    # Health check configuration
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    # Optional: Restrict access by source IP (uncomment and modify as needed)
    # service.beta.kubernetes.io/aws-load-balancer-source-ranges: "YOUR.IP.ADDRESS.HERE/32"
spec:
  type: LoadBalancer
  selector:
    app: cuda-eval-server-v2
    gpu-type: a100
  ports:
  - name: http
    port: 80          # Standard HTTP port for external access
    targetPort: 8000  # Port on the container
    protocol: TCP
  sessionAffinity: None  # Round-robin load balancing